apiVersion: webhookconfig.keptn.sh/v1beta1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.finished
      requests:
        - url: https://keptn-sp.atlassian.net/rest/api/3/issue
          payload: >-
            {"fields":{"summary":"Testing {{.data.project}} project in {{.data.stage}} stage {{.data.result}}","parent":{"key":"OPP6-3"},"issuetype":{"id":"10009"},"project":{"id":"10004"},"description":{"type":"doc","version":1,"content":[{"type":"paragraph","content":[{"text":"Testing delivery pipeline quality gate {{.data.result}} when passing through.","type":"text"}]}]},"reporter":{"id":"62d581b283067f68f84fe736"},"labels":["bugfix","blitz_test"]}}
          headers:
            - key: Accept
              value: application/json
            - key: Content-Type
              value: application/json
            - key: Authorization
              value: Basic {{.env.secret_apitok_Token}}
          method: POST
      envFrom:
        - name: secret_apitok_Token
          secretRef:
            name: apitok
            key: Token
      subscriptionID: 40d6cd1e-ef47-4423-a0b8-28979cef4430
      sendFinished: true
      sendStarted: true
    - type: sh.keptn.event.je-deployment.triggered
      requests:
        - url: https://events.pagerduty.com/v2/enqueue
          payload: >-
            {  "payload": {    "summary": "DISK at 99% on machine prod-datapipe03.example.com",    "timestamp": {{.time}},    "severity": "critical {{.type}} {{.data.result}} {{.data.status}}",    "source": "http://152.67.28.185/bridge/project/myapp/",    "component": "qa",    "group": "prod-datapipe"  },  "routing_key": "55ddf4914b4a4904c0776c7896eab557",  "dedup_key": "srv01/qa",  "event_action": "trigger",  "client": "Sample Monitoring Service",  "client_url": "http://152.67.28.185/bridge"}
          headers:
            - key: Content-Type
              value: application/json
          method: POST
      subscriptionID: bd20717d-adc3-4982-acd3-c41c96df8b00
      sendFinished: true
      sendStarted: true
